---
- hosts: control_plane
  become: yes
  tasks:
    - name: check_apiserver
      copy:
        dest: "/etc/keepalived/check_apiserver.sh"
        content: |
          #!/bin/sh
          
          errorExit() {
              echo "*** $*" 1>&2
              exit 1
          }
          
          curl --silent --max-time 2 --insecure https://localhost:{{ VIRTUAL_IP_PORT }}/ -o /dev/null || errorExit "Error GET https://localhost:${APISERVER_DEST_PORT}/"
          if ip addr | grep -q {{ VIRTUAL_IP }}; then
              curl --silent --max-time 2 --insecure https://{{ VIRTUAL_IP }}:{{ VIRTUAL_IP_PORT }}/ -o /dev/null || errorExit "Error GET https://{{ VIRTUAL_IP }}:{{ VIRTUAL_IP_PORT }}/"
          fi

    - name: apply bridge network
      become: yes
      shell: chmod +x /etc/keepalived/check_apiserver.sh


    - name: haproxy
      copy:
        dest: "/etc/haproxy/haproxy.cfg"
        content: |
          global
            log /dev/log local0
            log /dev/log local1 notice
            daemon
          
          defaults
            log                     global
            option                  httplog
            option                  dontlognull
            #maxconn 20000
            #mode    tcp
            #option  dontlognull
            #timeout http-request 10s
            #timeout queue        1m
            timeout connect      10s
            timeout client       86400s
            timeout server       86400s
            #timeout tunnel       86400s

          frontend k8s-apiserver
            bind 0.0.0.0:{{ VIRTUAL_IP_PORT }}
            mode tcp
            option tcplog
            default_backend k8s-apiserver
            
          backend k8s-apiserver
            mode tcp
            # option tcplog
            option tcp-check
            balance roundrobin
            default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100 
            
            server kcontrolplane1 {{ IP_HOST_CP1 }}:6443 check
            server kcontrolplane2 {{ IP_HOST_CP2 }}:6443 check
            server kcontrolplane3 {{ IP_HOST_CP3 }}:6443 check

- hosts: control1
  become: yes
  tasks:
    - name: keepalived
      copy:
        dest: "/etc/keepalived/keepalived.conf"
        content: |
          global_defs {
              router_id LVS_DEVEL
          }
          vrrp_script check_apiserver {
            script "/etc/keepalived/check_apiserver.sh"
            interval 3
            weight -2
            fall 10
            rise 2
          }
          
          vrrp_instance VI_1 {
              state MASTER
              interface eth1
              virtual_router_id 51
              priority 101
              authentication {
                  auth_type PASS
                  auth_pass iech6peeBu6Thoo8xaih
              }
              virtual_ipaddress {
                  {{ VIRTUAL_IP }}
              }
              track_script {
                  check_apiserver
              }
          }

- hosts: control2
  become: yes
  tasks:
    - name: keepalived
      copy:
        dest: "/etc/keepalived/keepalived.conf"
        content: |
          global_defs {
              router_id LVS_DEVEL
          }
          vrrp_script check_apiserver {
            script "/etc/keepalived/check_apiserver.sh"
            interval 3
            weight -2
            fall 10
            rise 2
          }
          
          vrrp_instance VI_1 {
              state BACKUP
              interface eth1
              virtual_router_id 51
              priority 100
              authentication {
                  auth_type PASS
                  auth_pass iech6peeBu6Thoo8xaih
              }
              virtual_ipaddress {
                  {{ VIRTUAL_IP }}
              }
              track_script {
                  check_apiserver
              }
          }
          
- hosts: control3
  become: yes
  tasks:
    - name: keepalived
      copy:
        dest: "/etc/keepalived/keepalived.conf"
        content: |
          global_defs {
              router_id LVS_DEVEL
          }
          vrrp_script check_apiserver {
            script "/etc/keepalived/check_apiserver.sh"
            interval 3
            weight -2
            fall 10
            rise 2
          }
          
          vrrp_instance VI_1 {
              state BACKUP
              interface eth1
              virtual_router_id 51
              priority 101
              authentication {
                  auth_type PASS
                  auth_pass iech6peeBu6Thoo8xaih
              }
              virtual_ipaddress {
                  {{ VIRTUAL_IP }}
              }
              track_script {
                  check_apiserver
              }
          }


- hosts: control_plane
  become: yes
  tasks:
    - name: keepalived services
      ansible.builtin.systemd:
        state: restarted
        name: keepalived

    - name: haproxy services
      ansible.builtin.systemd:
        state: restarted
        name: haproxy